### ISSUE TITLE
Aniworld.to Support

### ISSUE THREAD

**Issue by xXseesXx** [Bungeefan/SerienStreamControls#1]
can you add support for the related website aniworld.to

**Comment by Bungeefan** [comment]
Will have to check, however as the interface seems to be very similar, it should probably be simple to add it.

**Comment by Bungeefan** [comment]
[Version 1.4](https://addons.mozilla.org/de/firefox/addon/serienstream-controls/) with Aniworld.to support has been published on the add-on store.

You need to click the extension icon once when accessing AniWorld to enable access to the website.
